jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 5000
#  error:
#    whitelabel:
#      enabled: false

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/supportportal
#    password: Qwerty@12345
#    username: root
  datasource:
    url: jdbc:mysql://database-1.cogned1c1glo.ap-south-1.rds.amazonaws.com:3306/supportportal
    password: Qwerty12345
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false